name: Check Icon PR
on: pull_request
jobs:
  check:
    name: Check the `devicon.json` and the SVGs' quality
    runs-on: ubuntu-18.04
    if: startsWith(github.event.pull_request.title, 'new icon') || startsWith(github.event.pull_request.title, 'update icon')  # only checks icon PR
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-python@v2
        with: 
          python-version: 3.8

      - name: Install dependencies 
        run: |
          python -m pip install --upgrade pip
          pip install -r ./.github/scripts/requirements.txt

      - name: Run the check_svg script
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_NUMBER: ${{ github.event.number }}
        run: python ./.github/scripts/check_icon_pr.py "$TOKEN" "$PR_TITLE" "$PR_NUMBER" ./icons ./devicon.json

      - name: Upload the err messages
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: err_messages
          path: ./err_messages.txt

      - name: Save the pr num in an artifact
        shell: bash
        if: success()
        env:
          PR_NUM: ${{ github.event.number }}
        run: echo $PR_NUM > pr_num.txt

      - name: Upload the pr num
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: pr_num
          path: ./pr_num.txt
